DROP TABLE if exists DISCIPLIN;
DROP TABLE if exists MEDLEM_DISCIPLIN;
DROP TABLE if exists MEDLEMMER;
DROP TABLE if exists TRÆNER;

CREATE TABLE TRÆNER (
    træner_ID INTEGER not null,
    træner_navn VARCHAR(30),
    primary key (træner_ID)
);

CREATE TABLE MEDLEMMER (  
    NAVN VARCHAR(30),
    ALDER INTEGER not null,
    TELEFONNUMMER INTEGER not null,
    MEDLEMSNUMMER INTEGER not null AUTO_INCREMENT,
    DATOOPRETTET TIMESTAMP,
    RESTANCE TINYINT,
    KONKURRENCESVØMMER TINYINT,
    træner_ID INTEGER,
    passiv tinyint,
    PRIMARY KEY (MEDLEMSNUMMER),
    FOREIGN KEY (træner_ID) REFERENCES TRÆNER(træner_ID)
);

CREATE TABLE MEDLEM_DISCIPLIN (
tid time,
MEDLEMSNUMMER int,
DISCIPLIN VARCHAR(30),
FOREIGN KEY (MEDLEMSNUMMER) REFERENCES MEDLEMMER(MEDLEMSNUMMER)
);

commit;
