DROP TABLE if exists BUTTERFLY;
DROP TABLE if exists CRAWL;
DROP TABLE if exists RYGCRAWL;
DROP TABLE if exists BRYSTSVØMNING;
DROP TABLE if exists MEDLEMMER;




CREATE TABLE MEDLEMMER (  
    ALDER INTEGER not null, 
    NAVN VARCHAR(30), 
    TELEFONNUMMER INTEGER not null,
    MEDLEMSNUMMER INTEGER not null AUTO_INCREMENT,
    DATOOPRETTET TIMESTAMP,
    BETALT TINYINT,
    KONKURRENCESVØMMER TINYINT,
    TRÆNER VARCHAR(30),
    PRIMARY KEY (MEDLEMSNUMMER)
);

insert into MEDLEMMER (navn, alder, TELEFONNUMMER, MEDLEMSNUMMER, DATOOPRETTET, BETALT, KONKURRENCESVØMMER, TRÆNER)
values ("Robert", 57, 55555555, 1, now(), 1, 1, "Hans Erik");


CREATE TABLE BUTTERFLY (
    TID time,
    MEDLEMSNUMMER int not null auto_increment,
    FOREIGN KEY (MEDLEMSNUMMER) REFERENCES MEDLEMMER(MEDLEMSNUMMER)
);

CREATE TABLE CRAWL (
    TID time,
    MEDLEMSNUMMER int not null auto_increment,
    FOREIGN KEY (MEDLEMSNUMMER) REFERENCES MEDLEMMER(MEDLEMSNUMMER)
);

CREATE TABLE RYGCRAWL (
    TID time,
    MEDLEMSNUMMER int not null auto_increment,
    FOREIGN KEY (MEDLEMSNUMMER) REFERENCES MEDLEMMER(MEDLEMSNUMMER)
);

CREATE TABLE BRYSTSVØMNING (
    TID time,
    MEDLEMSNUMMER int not null auto_increment,
    FOREIGN KEY (MEDLEMSNUMMER) REFERENCES MEDLEMMER(MEDLEMSNUMMER)
);



commit;